package com.theokanning.openai.completion.chat;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.Getter;

import java.util.HashMap;
import java.util.Map;

/**
 * A chat completion generated by OpenAI
 */
@Data
public class ChatCompletionChoice {

    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    /**
     * The {@link ChatMessageRole#ASSISTANT} message or delta (when streaming) which was generated
     */
    @JsonAlias("delta")
    ChatMessage message;

    /**
     * The reason why GPT stopped generating, for example "length".
     */
    @JsonProperty("finish_reason")
    String finishReason;

    /**
     * Custom response attributes that are not part of the core OpenAI API.
     */
    @Getter(onMethod = @__(@JsonAnyGetter))
    Map<String, Object> extensions;

    /**
     * Consumes unknown JSON attributes and adds them to {@link #extensions}.
     */
    @JsonAnySetter
    public void handleIgnored(String name, Object value) {
        if (extensions == null) {
            extensions = new HashMap<>();
        }
        extensions.put(name, value);
    }
}
