package io.github.panghy.openai.edit;

import lombok.Builder;
import lombok.Data;
import lombok.extern.jackson.Jacksonized;

/**
 * An edit generated by OpenAi
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
@Data
@Jacksonized
@Builder
public class EditChoice {

    /**
     * The edited text.
     */
    String text;

    /**
     * This index of this completion in the returned list.
     */
    Integer index;
}
