package com.theokanning.openai.chat;

import lombok.Data;

/**
 * A completion generated by ChatGPT
 *
 * https://platform.openai.com/docs/api-reference/chat/create
 */
@Data
public class ChatCompletionChoice {

    /**
     * The generated message.
     */
    Message message;

    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    /**
     * The log probabilities of the chosen tokens and the top {@link ChatCompletionRequest#logprobs} tokens
     */
    ChatLogProbResult logprobs;

    /**
     * The reason why ChatGPT stopped generating, for example "length".
     */
    String finish_reason;
}
